service: onsight


provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:CreateTable
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: src/createComp.handler
    events:
      - http:
          path: competitions
          method: post
          cors: true
          authorizer: aws_iam

  list:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: src/getComps.handler
    events:
      - http:
          path: competitions
          method: get
          cors: true
          authorizer: aws_iam

  register:
    handler: src/register/registerCompetitor.handler
    events:
      - http:
          path: competitions/{compTable}
          method: post
          cors: true
          authorizer: aws_iam

  registerList:
      handler: src/register/getRegisteredCompetitors.handler
      events:
        - http:
            path: competitions/{compTable}
            method: get
            cors: true
            authorizer: aws_iam

  updateCompetitor:
        handler: src/register/updateCompetitor.handler
        events:
          - http:
              path: competitions/{compTable}/{competitorId}
              method: put
              cors: true
              authorizer: aws_iam

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**/*
  include:
    - src/*